messages = {
    "GAME OVER": "ИГРА ОКОНЧЕНА",
    "Enter - play again": "Enter - играть снова",
    "Pause": "ПАУЗА",
    "Score": "Очки",
    "Lines": "Линии",
    "Level": "Уровень",
    "Best Score": "Лучший счёт",
    "Move": "Движение",
    "Drop": "Сброс",
    "Rotate": "Поворот",
    "Quit": "Выход",
    "High Scores": "ЛУЧШИЕ РЕЗУЛЬТАТЫ",
    "Name": "Имя",
    "Points": "Очки",
    "Date": "Дата",
    "Time": "Время",
    "Press H for High Scores": "Нажмите H для просмотра рекордов",
    "Enter your name": "Введите ваше имя",
    "No scores yet": "Пока нет результатов",
    "Back to game": "Нажмите любую клавишу"
}
